// examples/shared/CardModalWrapper.vue
<script setup lang="ts">
import { ref, watch, onUnmounted } from 'vue'
import clsx from 'clsx'

// Импортируем ваши общие SCSS-модули
import baseClasses from '../ui.common.module.scss'
import btnClasses from '../ui.button.module.scss'

// Описываем интерфейс входных параметров (пропсов)
interface Props {
  title: string
  description?: string
  buttonText?: string
  className?: string
  footerText?: string
  useTwoColumns?: boolean
}

// Задаем значения по умолчанию для пропсов
const props = withDefaults(defineProps<Props>(), {
  buttonText: 'Show',
  useTwoColumns: false
})

// Локальное состояние открытия модального окна
const isOpen = ref(false)

// Блокируем прокрутку страницы body, когда модалка открыта
watch(isOpen, (newValue) => {
  if (newValue) {
    document.body.style.overflow = 'hidden'
  } else {
    document.body.style.overflow = ''
  }
})

// Сбрасываем стиль прокрутки при уничтожении (unmount) компонента карточки
onUnmounted(() => {
  document.body.style.overflow = ''
})
</script>

<template>
  <div
    :class="clsx(
      baseClasses.unit,
      baseClasses.stack2,
      props.className,
      { [baseClasses['unit--wide']]: props.useTwoColumns }
    )"
  >
    <!-- Метка-заголовок карточки в вашем фирменном стиле -->
    <div :class="baseClasses.absoluteUnitLabel">{{ props.title }}</div>

    <!-- Описание внутри карточки, если передано -->
    <p
      v-if="props.description"
      style="font-weight: bold; color: gray; margin: 0; font-family: system-ui;"
    >
      {{ props.description }}
    </p>

    <!-- Кнопка-триггер для открытия модалки -->
    <div style="margin-top: auto;">
      <button
        @click="isOpen = true"
        :class="clsx(
          btnClasses.btn,
          btnClasses.neonBtn,
          btnClasses['neonBtn--primary'],
          btnClasses['neonBtn--outlined']
        )"
      >
        {{ props.buttonText }}
      </button>
    </div>

    <!-- Модальное окно через Телепорт (Аналог createPortal на селектор body) -->
    <Teleport to="body">
      <div
        v-if="isOpen"
        style="
          position: fixed;
          top: 0;
          left: 0;
          width: 100vw;
          height: 100vh;
          background-color: rgba(255, 255, 255, 0.6);
          backdrop-filter: blur(4px);
          display: flex;
          align-items: flex-start;
          padding-top: 24px;
          justify-content: center;
          z-index: 9999;
        "
        @click="isOpen = false"
      >
        <div
          style="
            border: 2px solid lightgray;
            border-radius: 32px;
            min-width: 320px;
            max-width: calc(100vw - 48px);
            max-height: calc(100vh - 48px);
            position: relative;
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15);
            display: flex;
            flex-direction: column;
            overflow: hidden;
            background-color: #fff;
          "
          @click.stop
        >
          <!-- ФИКСИРОВАННАЯ ШАПКА МОДЛКИ -->
          <div
            style="
              position: relative;
              padding: 16px 52px 16px 24px;
              border-bottom: 2px solid lightgray;
              flex-shrink: 0;
            "
          >
            <h3 style="margin-top: 0; margin-bottom: 0; padding-right: 24px;">
              {{ props.title }}
            </h3>

            <!-- Кнопка закрытия (крестик) -->
            <button
              @click="isOpen = false"
              style="
                position: absolute;
                top: 0px;
                right: 16px;
                transform: translateY(45%);
                background: none;
                border: 2px solid lightgray;
                width: 35px;
                height: 35px;
                border-radius: 50%;
                color: gray;
                cursor: pointer;
                font-size: '20px';
                line-height: 1;
                padding: 0;
                display: flex;
                flex-direction: row;
                justify-content: center;
                align-items: center;
              "
            >
              <span>✕</span>
            </button>
          </div>

          <!-- СКРОЛЛЯЩАЯСЯ ОБЛАСТЬ С КОНТЕНТОМ -->
          <div
            style="
              padding: 24px;
              overflow-y: auto;
              flex-grow: 1;
            "
          >
            <div :class="baseClasses.stack2">
              <!-- Слот Vue. Сюда подставится переданный компонент (например, <Example003 />) -->
              <slot />
            </div>
          </div>

          <!-- ФУТЕР (Показывается только если передан проп footerText) -->
          <div
            v-if="props.footerText"
            style="
              font-family: system-ui;
              font-size: small;
              padding: 16px 24px;
              border-top: 2px solid lightgray;
              flex-shrink: 0;
            "
          >
            {{ props.footerText }}
          </div>

        </div>
      </div>
    </Teleport>
  </div>
</template>

// src/examples/shared/CardModalWrapper.tsx
import { useState, ReactNode, useEffect } from 'react'
import { createPortal } from 'react-dom'
import clsx from 'clsx'
import baseClasses from '../ui.common.module.scss'
import btnClasses from '../ui.button.module.scss'

interface CardModalWrapperProps {
  title: string;
  description?: string;
  buttonText?: string;
  children: ReactNode;
  className?: string;
  footerText?: string;
  useTwoColumns?: boolean;
}

export const CardModalWrapper = ({
  title,
  description,
  buttonText = 'Show',
  children,
  className,
  footerText,
  useTwoColumns,
}: CardModalWrapperProps) => {
  const [isOpen, setIsOpen] = useState(false)

  // Блокируем прокрутку страницы, когда модалка открыта
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden'
    } else {
      document.body.style.overflow = ''
    }
    return () => { document.body.style.overflow = '' }
  }, [isOpen])

  return (
    <div
      className={clsx(baseClasses.unit, baseClasses.stack2, className, { [baseClasses['unit--wide']]: useTwoColumns })}
    >
      {/* Метка-заголовок карточки в вашем фирменном стиле */}
      <div className={baseClasses.absoluteUnitLabel}>{title}</div>

      {/* Описание внутри карточки, если передано */}
      {description && <p style={{ fontSize: 'bold', color: 'gray', margin: 0, fontFamily: 'system-ui' }}>{description}</p>}

      {/* Кнопка-триггер для открытия */}
      <div>
        <button
          onClick={() => setIsOpen(true)}
          className={clsx(btnClasses.btn, btnClasses.neonBtn, btnClasses['neonBtn--primary'], btnClasses['neonBtn--outlined'])}
        >
          {buttonText}
        </button>
      </div>

      {/* Модальное окно через Портал */}
      {isOpen && createPortal(
        <div
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            width: '100vw',
            height: '100vh',
            backgroundColor: 'rgba(255, 255, 255, 0.6)',
            backdropFilter: 'blur(4px)',
            display: 'flex',
            alignItems: 'flex-start',
            paddingTop: '24px',
            justifyContent: 'center',
            zIndex: 9999
          }}
          onClick={() => setIsOpen(false)} // Закрытие при клике на оверлей
        >
          <div
            style={{
              // backgroundColor: '#fff', // Белый фон (можно сменить на темный)
              border: '2px solid lightgray',
              borderRadius: '32px',
              minWidth: '320px',
              maxWidth: 'calc(100vw - 24px - 24px)',
              maxHeight: 'calc(100vh - 24px - 24px)',
              position: 'relative',
              boxShadow: '0 10px 30px rgba(0,0,0,0.15)',
              display: 'flex',
              flexDirection: 'column', // Превращаем в flex-контейнер для изоляции скролла
              overflow: 'hidden' // Запрещаем скролл на самом верхнем контейнере карточки
            }}
            onClick={(e) => e.stopPropagation()} // Предотвращаем закрытие при клике внутри модалки
          >
            {/* ФИКСИРОВАННАЯ ШАПКА */}
            <div
              style={{
                position: 'relative',
                padding: '16px 52px 16px 24px', // Оставляем 48px справа, чтобы текст не налезал на крестик
                borderBottom: '2px solid lightgray', // Мягкая разделяющая линия (опционально)
                flexShrink: 0 // Запрещаем шапке сжиматься
              }}
            >
              <h3 style={{ marginTop: 0, marginBottom: 0, paddingRight: '24px' }}>{title}</h3>

              {/* Кнопка закрытия (крестик) теперь позиционируется относительно фиксированной шапки */}
              <button
                onClick={() => setIsOpen(false)}
                style={{
                  position: 'absolute',
                  top: '0px',
                  right: '16px',
                  transform: 'translateY(45%)',
                  background: 'none',
                  border: '2px solid lightgray',
                  width: '35px',
                  height: '35px',
                  borderRadius: '50%',
                  color: 'gray',
                  cursor: 'pointer',
                  fontSize: '20px',
                  lineHeight: 1,
                  padding: 0,
                  display: 'flex',
                  flexDirection: 'row',
                  justifyContent: 'center',
                  alignItems: 'center',
                }}
              >
                <span>✕</span>
              </button>
            </div>

            {/* СКРОЛЛЯЩАЯСЯ ОБЛАСТЬ С КОНТЕНТОМ */}
            <div
              style={{
                padding: '24px',
                overflowY: 'auto', // Скролл теперь живет только здесь
                flexGrow: 1 // Заставляем контент занимать всё оставшееся пространство по высоте
              }}
            >
              <div className={baseClasses.stack2}>
                {children}
              </div>
            </div>

            {
              !!footerText && (
                <div
                  style={{
                    fontFamily: 'system-ui',
                    fontSize: 'small',
                    padding: '16px 24px', // Оставляем 48px справа, чтобы текст не налезал на крестик
                    borderTop: '2px solid lightgray', // Мягкая разделяющая линия (опционально)
                    flexShrink: 0 // Запрещаем шапке сжиматься
                  }}
                >{footerText}</div>
              )
            }

          </div>
        </div>,
        document.body
      )}
    </div>
  )
}
